openapi: 3.0.0
info:
  title: IOS SDK
  description: A sample API
  version: "0.2.0"
# Basic authentication
components:
  securitySchemes:
    BasicAuth:
      type: http
      scheme: basic
security:
  - BasicAuth: []

# Since there are no paths, path: {} is empty
paths: {}
schemas:

  DojoCardPaymentPayload:
    type: object
    required:  
      - cardDetails
    properties:
      cardDetails:
        type: object
        properties:
          cardNumber:
            type: string
            example: "4456530000001096"
          cardName:
            type: string
            example: "Test Cardholder"
          expiryDate:
            type: string
            example: "12 / 24"
          cv2:
            type: string
            example: "020"
        required:  
          - cardNumber
      userEmailAddress:
        type: string
        example: "email@test.com"
      userPhoneNumber:
        type: string
        example: "0733323423"
